config/routes.rb
Rails.application.routes.draw do
  resources :categories

  root "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :parent, class_name: "Category"
  has_many :children, class_name: "Category", foreign_key: :parent_id

  scope :with_children, ->() { joins(:children).distinct }
  scope :top_level, ->() { where(parent_id: nil) }

  before_save :ensure_one_root

  ##
  # CLASS METHODS
  ##

  def self.root
    self.top_level.first
  end

  def self.make_root(other)
    self.transaction do
      old_root = self.root
      old_root.update_column(:parent_id, other.id)
      other.update_column(:parent_id, nil)
    end
  end

  ##
  # INSTANCE METHODS
  ##

  def siblings
    if parent
      parent.children.where.not(id: self.id)
    else
      Category.top_level.where.not(id: self.id)
    end
  end

  def has_parent?
    self.parent.present?
  end

  def is_leaf?
    self.children.empty?
  end

  def is_root?
    self.parent.nil?
  end

  def make_root
    self.class.make_root(self)
  end

  private

  def ensure_one_root
    return false if self == self.class.root
    self.parent = self.class.root if parent_id.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.top_level
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @parent = @category.parent
    @siblings = @category.siblings
    @children = @category.children
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
o<!-- Partial for displaying a category -->
<div class="category-item">
  <ul>
    <li>Name: <%= link_to category.name, category_path(category) %></li>
    <li>
        <% if category.parent %> <p>Parent: <%= category.parent.name %></p> <% end %>
    </li>
    <% if category.siblings %>
    <li>
      Siblings:
      <ul>
	<% category.siblings.each do |sibling| %>
	<li><%= link_to sibling.name, category_path(sibling) %></li>
	<% end %>
      </ul>
    </li>
    <% end %>
    <% unless category.children.empty? %>
    <li>
      Children:
      <blockquote>
	<%= render partial: category.children, locals: {shallow: false} %>
      </blockquote>
    </li>
    <% end %>
  </ul>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Full Category Listing</h1>

<%= render partial: @categories, locals: { shallow: false } %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @category %>

<%= link_to 'Categories List', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExampleNestedCategory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>